# Generated by Django 4.2.3 on 2023-07-10 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0002_rename_serial_number_ititem_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ititem',
            old_name='location',
            new_name='floor',
        ),
    ]
