# Generated by Django 4.2.3 on 2023-07-10 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0003_rename_location_ititem_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ititem',
            name='project',
        ),
    ]
