# Generated by Django 4.2.3 on 2023-07-10 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0004_remove_ititem_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.AlterField(
            model_name='ititem',
            name='warranty_period',
            field=models.IntegerField(default=10),
        ),
    ]
