# Generated by Django 4.2.3 on 2023-07-10 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0005_delete_project_alter_ititem_warranty_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ititem',
            old_name='service_tag',
            new_name='ser_no',
        ),
    ]
