# Generated by Django 4.2.3 on 2023-07-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IT', '0007_itstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itstore',
            name='amount_assigned',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='itstore',
            name='amount_left',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='itstore',
            name='total',
            field=models.IntegerField(default=''),
        ),
    ]
